### ISSUE TITLE
a+ voting arrows on Windows 10 broken?

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1584] opened 2021-11-17 13:12 UTC
**URL:** https://adhocracy.plus/obenandervolme/topicprio/2021-06548/
**user:** user
**expected behaviour:** voting arrows look normal
**behaviour:** voting arrows look a bit broken
**important screensize:**-
**device & browser:** Windows 10 Home, Firefox 94.0.1 (64-Bit)
**Comment/Question:** 
This bug was reported from a user. I could not reproduce it on my computer. Any ideas?

Screenshot from User (actually not a real screenshot):
![20211117_102841](https://user-images.githubusercontent.com/5470479/142206962-7b210c93-6e41-4864-843f-977d7d1bd349.jpg)

**Comment by phillimorland** [comment] 2022-01-12 16:35
might be

**Comment by fredewe** [comment] 2022-06-09 11:43
@phillimorland can we close this one as it is not our bug?

**Comment by goapunk** [comment] 2022-06-13 06:43
@phillimorland we have a test computer, yes

**Comment by fuzzylogic2000** [comment] 2023-06-16 13:29
@philli-m @goapunk Did we test this?
@lthueer Do you know if this happened again?

**Comment by goapunk** [comment] 2023-06-19 06:37
no idea, however testing should be easy enough with browserstack?

**Comment by lthueer** [comment] 2023-06-19 07:27
@fuzzylogic2000 @goapunk @philli-m I can't reproduce this problem even with Browserstack. Seems to work with all browsers on Windows 10, so close this issue

**Closed by lthueer** 2023-06-19 07:27 UTC
Labels: Dev: Not our bug, Dev: Styling
