### ISSUE TITLE
debate module: comment field stays extended

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#337] opened 2020-02-17 17:40 UTC
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00170/
**user:** Admin
**expected behaviour:** field for contribution closes/becomes smaller again after I added my comment
**behaviour:** field for contribution stays extended after I added a biiiiig comment. 
**important screensize:**
**device & browser:** 
**Comment/Question:** low prio

**Comment by phillimorland** [comment] 2020-02-18 12:49
@hmkay not sure what relevance the screen shot it? also cannot reproduce error, what browser were you on?

**Comment by hmkay** [comment] 2020-02-18 15:04
xD Yes. As you see: All empty! But actually I wasn´t sure if I made myself clear what I meant.

I was on Firefox, 73.0 (64-Bit)

**Comment by hmkay** [comment] 2020-02-18 15:04
@phillimorland : Low prio though, no milestone!

**Comment by hmkay** [comment] 2020-02-18 15:13
@phillimorland I just got it! Sorry! Wrong picture!! So forget about the picture.

**Comment by phillimorland** [comment] 2020-02-26 14:57
cannot reproduce on any browser so closing for now

**Closed by phillimorland** 2020-02-26 14:57 UTC
Labels: Type: Bug
