### ISSUE TITLE
map does not load

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#686] opened 2020-07-13 09:08 UTC
**URL:** https://adhocracy.plus/musterorganisation/projects/module/brainstorming-mit-karte-4/
**user:** any
**expected behaviour:** i can see map
**behaviour:** map does not load at least in citizens budget and brainstorming with map
**important screensize:**
**device & browser:** mac, chrome
**Comment/Question:** 

Screenshot?
<img width="572" alt="Bildschirmfoto 2020-07-13 um 11 05 54" src="https://user-images.githubusercontent.com/35491681/87286414-21ba9c00-c4f9-11ea-8b29-0615a637ec86.png">

**Comment by phillimorland** [comment] 2020-07-13 10:07
@CarolingerSeilchenspringer what version of Chrome are you using? have tested on 2 machines and maps are loading fine

**Comment by CarolingerSeilchenspringer** [comment] 2020-07-13 10:16
@phillimorland Version 83.0.4103.116. Could it be any other setting?

**Comment by phillimorland** [comment] 2020-07-13 10:19
@CarolingerSeilchenspringer that's same version as mine, can you clear your cache and let me know? that's all i can think of, it's working on my mobile and 2 laptops so I would normally close this

**Comment by CarolingerSeilchenspringer** [comment] 2020-07-13 10:42
@phillimorland no, clearing my cache did not help nor did a restart of my mac.

**Comment by phillimorland** [comment] 2020-07-13 11:15
cannot reproduce on multiple devices so will close

**Closed by phillimorland** 2020-07-13 11:15 UTC
Labels: Prio: Critical, Type: Bug

**Comment by phillimorland** [comment] 2020-07-13 11:16
@CarolingerSeilchenspringer i've added a reminder to myself to keep an eye on maps, will reopen if there is a case on another device

**Comment by CarolingerSeilchenspringer** [comment] 2020-07-13 11:26
@phillimorland I deinstalled my ghostery plug in, that helped. Reinstalling it, map is still working.
