### ISSUE TITLE
Edit organization/project slug

### ISSUE THREAD

**Issue by oriyalperin** [liqd/adhocracy-plus#2734] opened 2024-07-25 06:13 UTC
Is there a way for an organization initiator to edit the organization or project slug?

**Comment by erelsgl** [comment] 2024-07-28 11:20
The problem is that, if the project title is not in English, the URL does not fit the name of the project or organization. 
What is the best way to handle slugs for non-English titles?

**Comment by TeaJayyy** [comment] 2024-07-31 06:17
@oriyalperin Currently, it is not possible for initiators to change any URL slug. The idea of implementing this feature has existed for quite some time but has not been prioritized highly.

**Comment by oriyalperin** [comment] 2024-07-31 07:37
> @erelsgl Could you describe the problem in more detail?

Thanks @TeaJayyy,
we tried creating an organization with a Hebrew name, but the slug generated was just "organization".
The same thing happened with a Hebrew project name, resulting in the slug "project",
so, the project URL is:
http://localhost:8004/organisation/projects/project/

We want the slugs to be meaningful and reflect the actual Hebrew names. How can we achieve this?

**Comment by TeaJayyy** [comment] 2024-07-31 11:42
@erelsgl Assuming you chose an organisation name written in Hebrew letters, I think there is no "translation" into the Latin alphabet. Correct me if I'm wrong here. Maybe @goapunk can give you a more elaborate answer.

**Comment by erelsgl** [comment] 2024-07-31 12:17
There is also a problem when creating several different organizations / projects with different Hebrew names. It is very hard to distinguish between them.

**Comment by goapunk** [comment] 2024-07-31 12:26
@erelsgl There's currently no way to change the slug for an organisation (except via the django shell). For projects you can change the slug via the django-admin. Could you give us an example of a project name which fails so we can investigate the issue. The slugs are auto-generated via the django-autoslug package, so I assume the issue comes from there, e.g. https://github.com/justinmayer/django-autoslug/issues/85

**Comment by oriyalperin** [comment] 2024-08-01 10:33
@goapunk if I manually change the slug as you suggested, will it automatically update in the URLs of all content that relies on that slug?

**Comment by goapunk** [comment] 2024-08-01 10:35
@oriyalperin If you change a project slug everything should still work within a+ (if you shared the link to the project with someone the old link will not work any more of course)

**Comment by TeaJayyy** [comment] 2024-09-06 18:01
Closing this issue (edit slug) but created an entry in the backlog for the future. By the way, we'd be happy to receive a PR from you if you want to tackle this. Regarding the autoslug, we will have an eye on it but keeping it as an [issue](https://github.com/liqd/adhocracy-plus/issues/2736) for the moment. Thanks for your contributions! :)

**Closed by TeaJayyy** 2024-09-06 18:01 UTC
Labels: Type: Feature-request
