### ISSUE TITLE
dashboard: delete project delay

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1094] opened 2021-02-04 13:14 UTC
**URL:** https://aplus-stage.liqd.net/liqd/dashboard/organisations/projects/
**user:** initiators, admins
**expected behaviour:** you can simply delete or duplicate a project
**behaviour:** there is a delay in the dropdown for "delete" and "duplicate" if the project title is too long. 
**important screensize:**
**device & browser:** 
**Comment/Question:** For short titles it works. I tested it and to me it appears that the issue occurs if the project title is longer than 21 characters.

![Bildschirmfoto 2021-02-04 um 14 13 29](https://user-images.githubusercontent.com/36957474/106897469-4378ac00-66f3-11eb-8c94-c462327e52e7.png)

**Comment by phillimorland** [comment] 2021-03-04 17:23
closing as duplicate of #1062

**Closed by phillimorland** 2021-03-04 17:23 UTC
Labels: Type: UX/UI or design
